### ISSUE TITLE
Lathe.ai documentation not available.

### ISSUE THREAD

**Issue by jasonminsookim** [emmettgb/Lathe.jl#43]
I clicked on the documentation link in the readme, but got nothing.

**Comment by emmettgb** [comment]
Hi Jason, we are currently migrating servers. The best way to access the documentation would be through code.
`julia
using Lathe
?(stats)`

**Comment by emmettgb** [comment]
Closing this issue, as new html documentation can now be found at : https://juliahub.com/docs/Lathe/6rMNJ/0.1.2/
