### ISSUE TITLE
FYI: Breaking change?

### ISSUE THREAD

**Issue by PallHaraldsson** [emmettgb/Lathe.jl#47]
Hi,

I noticed you're registering 0.1.3, but while I didn't look carefully, it seems you're deleting a lot of stuff, and then if this is a breaking change the version number should be 0.2.0. Even with 0.x semver holds for Julia packages, then breaking changes up the 0.x.0, for 1.x.y and higher, breaking changes up the first number.

**Comment by emmettgb** [comment]
The deletions were some bad commits made from my machine where src/models/* was accidentally committed to src/* -- whoops.
Syntactically, there aren't many changes. The biggest changes are as follows:
Stats now works off of distribution objects, and you can test by providing distributions and data as a parameter. Right now I haven't diven into the cummulative distribution functions, but you can still get your stat and lookup on a table to get a proper P value.
Furthermore, documentation for most of stats, all of preprocess, and the new models is now over-hauled with markdown.
Additionally, there is the addition of  the RandomForestClassifier and DecisionTreeClassifier.
Lastly, consistency for pipelining is now universal. The objects for preprocess that use distributions now call on lstats distribution objects.
Todo on these updates:
Cdf (obviously)
More pdfs (thinking F, binomial revision, bernealli)
The nueral implementation needs modular layers, also am working on some time series lstm stuff in terms of that.
Improved documentation on functions that are unrevised.
Also -
Julia won't let you skip a version -- even so each version has a respective branch add Lathe#0.1.x
