### ISSUE TITLE
Preprocessing - add Quantile scaler - new feature request

### ISSUE THREAD

**Issue by gugatr0n1c** [emmettgb/Lathe.jl#55]
Hello,

great job this package. Finally something close to scikit learn :-).
Is it possible to add new preprocossing scaler?
Uniform a Normal mapping from empirical cdf.

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.QuantileTransformer.html#sklearn.preprocessing.QuantileTransformer

thanks

**Comment by emmettgb** [comment]
https://github.com/emmettgb/Lathe.jl/commit/85aebfadcc02a593460e00dfdc954fe88a7fab42
https://github.com/emmettgb/Lathe.jl/commit/004d42d93279d416a466dd0892e46867284dd515
004d42d93279d416a466dd0892e46867284dd515 merged => #Unstable
