### ISSUE TITLE
Allow DataFrames.jl 0.22

### ISSUE THREAD

**Issue by bkamins** [emmettgb/Lathe.jl#56]
We have released DataFrames.jl 0.22. You could consider allowing this version in your package. Thank you!

**Comment by emmettgb** [comment]
https://github.com/emmettgb/Lathe.jl/commit/004d42d93279d416a466dd0892e46867284dd515
Closed and pushed to unstable.

**Comment by emmettgb** [comment]
https://github.com/emmettgb/Lathe.jl/commit/20e2e45ffe0c34f1d24c8fffcdedd3fc6cabcb4f
Whoops wrong commit

**Comment by bkamins** [comment]
Thank you!
